//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://send_sms.vienthongdidong.vn/", ConfigurationName="ServiceReference1.send")]
    public interface send
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.sendResponse> sendAsync(ServiceReference1.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/getipRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/getipResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getipResponse> getipAsync(ServiceReference1.getipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQuestionRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQuestionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.sendQuestionResponse> sendQuestionAsync(ServiceReference1.sendQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/checkTransRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/checkTransResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.checkTransResponse> checkTransAsync(ServiceReference1.checkTransRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/QuestionRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/QuestionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.QuestionResponse> QuestionAsync(ServiceReference1.QuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/checkBalanceRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/checkBalanceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.checkBalanceResponse> checkBalanceAsync(ServiceReference1.checkBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendCskhRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendCskhResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.sendCskhResponse> sendCskhAsync(ServiceReference1.sendCskhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQcRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQcResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.sendQcResponse> sendQcAsync(ServiceReference1.sendQcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQc2Request", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQc2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.sendQc2Response> sendQc2Async(ServiceReference1.sendQc2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/AdsSendRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/AdsSendResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.AdsSendResponse> AdsSendAsync(ServiceReference1.AdsSendRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://send_sms.vienthongdidong.vn/")]
    public partial class sendsmsresponse
    {
        
        private string detailField;
        
        private string idTranField;
        
        private string receiptField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idTran
        {
            get
            {
                return this.idTranField;
            }
            set
            {
                this.idTranField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string receipt
        {
            get
            {
                return this.receiptField;
            }
            set
            {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        public sendRequest()
        {
        }
        
        public sendRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public sendResponse()
        {
        }
        
        public sendResponse(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getip", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class getipRequest
    {
        
        public getipRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getipResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class getipResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getipResponse()
        {
        }
        
        public getipResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQuestion", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQuestionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDQues;
        
        public sendQuestionRequest()
        {
        }
        
        public sendQuestionRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ, string IDQues)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
            this.IDQues = IDQues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQuestionResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQuestionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public sendQuestionResponse()
        {
        }
        
        public sendQuestionResponse(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkTrans", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkTransRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        public checkTransRequest()
        {
        }
        
        public checkTransRequest(string transid, string USERNAME)
        {
            this.transid = transid;
            this.USERNAME = USERNAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkTransResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkTransResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public checkTransResponse()
        {
        }
        
        public checkTransResponse(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Question", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class QuestionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUESTION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANSWER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDCLIENT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANSCORRECT;
        
        public QuestionRequest()
        {
        }
        
        public QuestionRequest(string USERNAME, string QUESTION, string ANSWER, string IDCLIENT, string ANSCORRECT)
        {
            this.USERNAME = USERNAME;
            this.QUESTION = QUESTION;
            this.ANSWER = ANSWER;
            this.IDCLIENT = IDCLIENT;
            this.ANSCORRECT = ANSCORRECT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuestionResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class QuestionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QuestionResponse()
        {
        }
        
        public QuestionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkBalance", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public checkBalanceRequest()
        {
        }
        
        public checkBalanceRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkBalanceResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkBalanceResponse()
        {
        }
        
        public checkBalanceResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCskh", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendCskhRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        public sendCskhRequest()
        {
        }
        
        public sendCskhRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string PHONE, string IDREQ)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCskhResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendCskhResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public sendCskhResponse()
        {
        }
        
        public sendCskhResponse(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQc", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        public sendQcRequest()
        {
        }
        
        public sendQcRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQcResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public sendQcResponse()
        {
        }
        
        public sendQcResponse(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQc2", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQc2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendtime;
        
        public sendQc2Request()
        {
        }
        
        public sendQc2Request(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ, string sendtime)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
            this.sendtime = sendtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQc2Response", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQc2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public sendQc2Response()
        {
        }
        
        public sendQc2Response(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdsSend", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class AdsSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendtime;
        
        public AdsSendRequest()
        {
        }
        
        public AdsSendRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string[] PHONE, string IDREQ, string sendtime)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
            this.sendtime = sendtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdsSendResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class AdsSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sendsmsresponse @return;
        
        public AdsSendResponse()
        {
        }
        
        public AdsSendResponse(ServiceReference1.sendsmsresponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface sendChannel : ServiceReference1.send, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class sendClient : System.ServiceModel.ClientBase<ServiceReference1.send>, ServiceReference1.send
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public sendClient() : 
                base(sendClient.GetDefaultBinding(), sendClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.sendPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sendClient(EndpointConfiguration endpointConfiguration) : 
                base(sendClient.GetBindingForEndpoint(endpointConfiguration), sendClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sendClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(sendClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sendClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(sendClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sendClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendResponse> ServiceReference1.send.sendAsync(ServiceReference1.sendRequest request)
        {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendResponse> sendAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ)
        {
            ServiceReference1.sendRequest inValue = new ServiceReference1.sendRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            return ((ServiceReference1.send)(this)).sendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getipResponse> ServiceReference1.send.getipAsync(ServiceReference1.getipRequest request)
        {
            return base.Channel.getipAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getipResponse> getipAsync()
        {
            ServiceReference1.getipRequest inValue = new ServiceReference1.getipRequest();
            return ((ServiceReference1.send)(this)).getipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendQuestionResponse> ServiceReference1.send.sendQuestionAsync(ServiceReference1.sendQuestionRequest request)
        {
            return base.Channel.sendQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendQuestionResponse> sendQuestionAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ, string IDQues)
        {
            ServiceReference1.sendQuestionRequest inValue = new ServiceReference1.sendQuestionRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.IDQues = IDQues;
            return ((ServiceReference1.send)(this)).sendQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.checkTransResponse> ServiceReference1.send.checkTransAsync(ServiceReference1.checkTransRequest request)
        {
            return base.Channel.checkTransAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.checkTransResponse> checkTransAsync(string transid, string USERNAME)
        {
            ServiceReference1.checkTransRequest inValue = new ServiceReference1.checkTransRequest();
            inValue.transid = transid;
            inValue.USERNAME = USERNAME;
            return ((ServiceReference1.send)(this)).checkTransAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.QuestionResponse> ServiceReference1.send.QuestionAsync(ServiceReference1.QuestionRequest request)
        {
            return base.Channel.QuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.QuestionResponse> QuestionAsync(string USERNAME, string QUESTION, string ANSWER, string IDCLIENT, string ANSCORRECT)
        {
            ServiceReference1.QuestionRequest inValue = new ServiceReference1.QuestionRequest();
            inValue.USERNAME = USERNAME;
            inValue.QUESTION = QUESTION;
            inValue.ANSWER = ANSWER;
            inValue.IDCLIENT = IDCLIENT;
            inValue.ANSCORRECT = ANSCORRECT;
            return ((ServiceReference1.send)(this)).QuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.checkBalanceResponse> ServiceReference1.send.checkBalanceAsync(ServiceReference1.checkBalanceRequest request)
        {
            return base.Channel.checkBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.checkBalanceResponse> checkBalanceAsync(string username, string password)
        {
            ServiceReference1.checkBalanceRequest inValue = new ServiceReference1.checkBalanceRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ServiceReference1.send)(this)).checkBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendCskhResponse> ServiceReference1.send.sendCskhAsync(ServiceReference1.sendCskhRequest request)
        {
            return base.Channel.sendCskhAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendCskhResponse> sendCskhAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string PHONE, string IDREQ)
        {
            ServiceReference1.sendCskhRequest inValue = new ServiceReference1.sendCskhRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            return ((ServiceReference1.send)(this)).sendCskhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendQcResponse> ServiceReference1.send.sendQcAsync(ServiceReference1.sendQcRequest request)
        {
            return base.Channel.sendQcAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendQcResponse> sendQcAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ)
        {
            ServiceReference1.sendQcRequest inValue = new ServiceReference1.sendQcRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            return ((ServiceReference1.send)(this)).sendQcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendQc2Response> ServiceReference1.send.sendQc2Async(ServiceReference1.sendQc2Request request)
        {
            return base.Channel.sendQc2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendQc2Response> sendQc2Async(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ, string sendtime)
        {
            ServiceReference1.sendQc2Request inValue = new ServiceReference1.sendQc2Request();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.sendtime = sendtime;
            return ((ServiceReference1.send)(this)).sendQc2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AdsSendResponse> ServiceReference1.send.AdsSendAsync(ServiceReference1.AdsSendRequest request)
        {
            return base.Channel.AdsSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AdsSendResponse> AdsSendAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string[] PHONE, string IDREQ, string sendtime)
        {
            ServiceReference1.AdsSendRequest inValue = new ServiceReference1.AdsSendRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.sendtime = sendtime;
            return ((ServiceReference1.send)(this)).AdsSendAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.sendPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.sendPort))
            {
                return new System.ServiceModel.EndpointAddress("http://210.211.109.118/apibrandname/send");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return sendClient.GetBindingForEndpoint(EndpointConfiguration.sendPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return sendClient.GetEndpointAddress(EndpointConfiguration.sendPort);
        }
        
        public enum EndpointConfiguration
        {
            
            sendPort,
        }
    }
}
