name: CICD

on:
  workflow_dispatch:
    inputs:
      service:
        options:
          - all
          - api
          - web
        required: true
        type: choice
        description: Choose which service to run

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      
    - name: Build and Push API
      if: ${{ github.event.inputs.service == 'api' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_topup_api
      with:
        context: ./
        file: ./src/HLS.Topup.Web.Host/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_api
        
    - name: Build and Push WEB
      if: ${{ github.event.inputs.service == 'web' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_topup_web
      with:
        context: ./
        file: ./src/HLS.Topup.Web.Mvc/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_web
